name: misslog
description: A simple, better log for your Flutter debugging.
version: 2.0.0
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  


# The following section is specific to Flutter.
flutter:

